### ISSUE TITLE
这个 commit 引入了不少 Bug

### ISSUE THREAD

**Issue by MilkBiscuit** [yangyxd/flutter_picker#102]
这个 commit https://github.com/yangyxd/flutter_picker/commit/c7e2a48d5d0907c853e29a113e6b77f66bedce01 引入了不少 Bug

这个 PR https://github.com/yangyxd/flutter_picker/pull/101 我只改了 Number Picker，但是看上去 demo 里的 Picker show icons 也有问题，两边的 Picker 显示的 icon 不应该一致。

**Expected Result:**
<img width="384" alt="Screen Shot 2020-05-13 at 9 03 38 PM" src="https://user-images.githubusercontent.com/20746964/81793313-4fb54b80-955d-11ea-92da-fc6bba069731.png">

**Actual Result:**
![device-2020-05-13-210235](https://user-images.githubusercontent.com/20746964/81793365-60fe5800-955d-11ea-81d4-36c4a1d756e0.png)

但是代码看不太懂，不确定该怎么改……

**Comment by MilkBiscuit** [comment]
搭车问，请问你可以在 Profile 留个邮箱吗？

<img width="1302" alt="Screen Shot 2020-05-07 at 10 54 58 PM" src="https://user-images.githubusercontent.com/20746964/81286917-fa3cf280-90b5-11ea-8166-2c980bd34b4d.png">

**Comment by yangyxd** [comment]
已修复 v1.1.5
