### ISSUE TITLE
NumberPickerAdapter not working

### ISSUE THREAD

**Issue by joaowd** [yangyxd/flutter_picker#103]
As the title says, NumberPickerAdapter stoped working since I update the version. I don't get any exception but the picker doesn't show up

**Comment by fenchai23** [comment]
The whole package is not working for me.

I think it has to do with the new Flutter **1.17.0** update changing the entire theming, most of my packages did not work unless I updated.

Maybe this package needs an update?

**Comment by joaowd** [comment]
I downgraded to the previous version and its working fine (1.1.3)

**Comment by fenchai23** [comment]
I went back to `1.1.3` and still the same thing.

![Snipaste_2020-05-09_11-38-40](https://user-images.githubusercontent.com/52770796/81479590-bcd98180-91e9-11ea-965a-23bac199b80c.png)

either that or the entire thing is empty.

```Dart
showCartItemQtyDiscountPricePicker(
      BuildContext context, cartItem, int index) {
    final List qtyList = Iterable<int>.generate(999, (i) => i + 1).toList();
    final List discountList =
        Iterable.generate(21, (i) => ((i) * 5).toString()).toList();
    Picker(
      adapter: PickerDataAdapter<String>(
        pickerdata: [
          {'Cantidad': qtyList},
          {'Descuento (%)': discountList},
          {
            'Precio': ['Manual']
          },
        ],
      ),
      cancelText: 'Cancelar',
      confirmText: 'Confirmar',
      changeToFirst: true,
      title: AutoSizeText(
        cartItem.code,
        style: Theme.of(context).textTheme.subtitle1,
      ),
      hideHeader: false,
      containerColor: Theme.of(context).cardTheme.color,
      backgroundColor: Theme.of(context).cardTheme.color,
      textStyle: Theme.of(context).textTheme.headline2,
      cancelTextStyle: Theme.of(context).textTheme.headline1,
      confirmTextStyle: Theme.of(context).textTheme.headline1,
      onConfirm: (Picker picker, List value) {
        if (value[0] == 1) {
          // descuento (%)
          Provider.of<CartDataProvider>(context, listen: false)
              .modifyCartItemDiscountPrice(index, ((value[1]) * 5).toString());
        } else if (value[0] == 0) {
          // cantidad
          Provider.of<CartDataProvider>(context, listen: false)
              .modifyCartItemQty((value[1] + 1).toString(), index);
        } else if (value[0] == 2) {
          // precio manual
          Future.delayed(const Duration(milliseconds: 500), () {
            // add small delay to allow modal to close
            // before showing the next picker
            // not tested on real devices
            showCartItemPricePicker(context, cartItem, index);
          });
        }
      },
    ).showModal(context);
  }
```


```
[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following RangeError was thrown during performLayout():[39;49m
RangeError (index): Invalid value: Not in range 0..2, inclusive: 4

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mMaterialApp[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      List.[]  (dart:core-patch/growable_array.dart:146:60)[39;49m
[38;5;248m#1      PickerDataAdapter.buildItem[39;49m
[38;5;248m#2      PickerWidgetState._buildViews.<anonymous closure>.<anonymous closure>[39;49m
[38;5;244m#3      ListWheelChildBuilderDelegate.build[39;49m
[38;5;244m#4      ListWheelElement.retrieveWidget.<anonymous closure>[39;49m
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: RenderListWheelViewport#4083f NEEDS-LAYOUT NEEDS-PAINT[39;49m
[38;5;244mRenderObject: RenderListWheelViewport#4083f NEEDS-LAYOUT NEEDS-PAINT[39;49m
    [38;5;244mneeds compositing[39;49m
    [38;5;244mparentData: <none> (can use size)[39;49m
    [38;5;244mconstraints: BoxConstraints(w=205.7, h=150.0)[39;49m
    [38;5;244msize: Size(205.7, 150.0)[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

```

Maybe I should create a separate issue...

**Comment by joaowd** [comment]
you need to remove the ^ from pubec

________________________________

**Comment by fenchai23** [comment]
`flutter_picker: 1.1.3` 

same error, I don't think it's the `^` causing this issue

**Comment by joaowd** [comment]
“RangeError (index): Invalid value: Not in range 0..2, inclusive: 4”

It doesn’t look like its library fault.

You have some range error in a list.

**Comment by fenchai23** [comment]
I haven't changed it since forever, also there seems to be some range issue because on pull request someone added an issue to fix the error which had some kind of range fix. check it out.

**Comment by fenchai23** [comment]
can you test my code on your Flutter Version? I think it's because mine is on **1.17.0**

**Comment by fenchai23** [comment]
this is just the default example for number picker
![image](https://user-images.githubusercontent.com/52770796/81480874-0b8b1980-91f2-11ea-8fd7-bb4d4d59c8ec.png)

You can see here pull request https://github.com/yangyxd/flutter_picker/pull/101
![image](https://user-images.githubusercontent.com/52770796/81480890-2067ad00-91f2-11ea-86f4-b729c2c07ebb.png)

**Comment by fenchai23** [comment]
weird, it's now working, maybe I needed a full restart. 1.1.3 worked

**Comment by perepechin** [comment]
> weird, it's now working, maybe I needed a full restart. 1.1.3 worked

1.1.3 version works for me as well even with the latest version of Flutter 1.17, but 1.1.4 doesn't work :/

**Comment by tonypottera24** [comment]
`flutter_picker: ^1.1.3` doesn't work with `v1.17.0` for me...

**Comment by fenchai23** [comment]
> `flutter_picker: ^1.1.3` doesn't work on `v1.17.0` for me...

remove ^ from 1.13

**Comment by pratih** [comment]
It does not work Flutter SDK 1.17.1. 

<img width="229" alt="Screenshot 2020-05-14 20 12 44" src="https://user-images.githubusercontent.com/16272731/82001022-b438df00-961f-11ea-89ef-4a8af17400d1.png">

**Comment by pratih** [comment]
Thank you for updating this! Version 1.1.5 now works with Flutter SDK 1.17.1.
