### ISSUE TITLE
二级联动列表错误

### ISSUE THREAD

**Issue by hongyanfengzi** [yangyxd/flutter_picker#106]
当只有两级列表联动的时候,  第二级列表数据是第一级的

**Comment by yangyxd** [comment]
已修复 v1.1.5

**Comment by hongyanfengzi** [comment]
`const PickerData = [
    {
      "a": [
        1,
        2,
        3,
      ]
    },
    {
      "b": [
        4,
        5,
        6,
      ]
    },
    {
      "c": [
        7,
        8,
        9,
      ]
    }
  ];`
升级为1.1.5版本, 这样的数据, PickerDataAdapter二级的数据还是第一级的

**Comment by hongyanfengzi** [comment]
用isArray来区分列表和联动, 应该用map的结构来处理联动, 才更合理点吧. 这是一点点个人看法!

**Comment by JsonYuu** [comment]
> 已修复 v1.1.5

还是有问题

**Comment by JsonYuu** [comment]
> 用isArray来区分列表和联动, 应该用map的结构来处理联动, 才更合理点吧. 这是一点点个人看法!



> `const PickerData = [ { "a": [ 1, 2, 3, ] }, { "b": [ 4, 5, 6, ] }, { "c": [ 7, 8, 9, ] } ];`
> 升级为1.1.5版本, 这样的数据, PickerDataAdapter二级的数据还是第一级的

请问你解决了吗
