### ISSUE TITLE
请问单列的选择怎么设置？ demo好像都是级联的

### ISSUE THREAD

**Issue by lj374055610** [yangyxd/flutter_picker#109]

**Comment by yangyxd** [comment]
单列直接用 CupertinoPicker 不香吗

**Comment by zzdota** [comment]
const PickerData = '''
[
       "阀值内",
       "阀值外"
]
    ''';
数据源改成这样，就成单列了。
![image](https://user-images.githubusercontent.com/16704305/130003538-d84ef279-46c5-490f-bdc2-6d2bee2387e5.png)
