### ISSUE TITLE
[Solved] Bug: Date numbers not refreshing correctly 

### ISSUE THREAD

**Issue by KostasKrv** [yangyxd/flutter_picker#11]
Hello, I noticed that when you are currently on a month with 31 days and scroll to a month with 30 then the day scroller updates and has now options until day 30 and that's totally correct! But if you now switch back to the month that has 31 days (generally to a month with more days than the one selected), the day scroller does not refresh and it's options remain until day 30. If you try to scroll the day then it refreshes correctly and day 31 is available again as an option.

Problem: ![Image of Bug](http://kostas.krevatas.net/stuff/uploads/2018/11/monthbug.gif)

**Comment by yangyxd** [comment]
Ha-ha, I know there will be such a problem, but also to deal with, but when the date is displayed in front of the time did not deal with. I will repair it as soon as possible. Thank you.

**Comment by KostasKrv** [comment]
The bug is now resolved at version 1.0.3. Very good job!
![Bug fixed](http://kostas.krevatas.net/stuff/uploads/2018/11/debug.gif)
