### ISSUE TITLE
弹出以后如何禁止手动下滑关闭picker?

### ISSUE THREAD

**Issue by xhanb** [yangyxd/flutter_picker#114]
当弹出以后，不点击取消或者确认，可以手动向下滑动使picker关闭，如何禁止该行为？
还有一个问题，如果底部有Tab导航，能默认从最低端弹出吗？目前会在Tab上面弹出

**Comment by yangyxd** [comment]
个性化的需求，建议使用 makePicker 生成选择器小部件后，其它功能自己实现。
