### ISSUE TITLE
自定义 Header

### ISSUE THREAD

**Issue by anchao-lu** [yangyxd/flutter_picker#119]
自定义 Header 画圆角无效
`builderHeader: (context) {
          return Container(
              decoration: BoxDecoration(
                  color: Color(0xffF5F5F5),
                  borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(12),
                      topRight: Radius.circular(12))),
              alignment: Alignment.center,
              height: 60,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: <Widget>[
                  Text(
                    '取消',
                    style: TextStyle(color: MAIN_COLOR, fontSize: 16),
                  ),
                  Text('1周',
                      style: TextStyle(color: Color(0xff333333), fontSize: 16)),
                  Text('确定', style: TextStyle(color: MAIN_COLOR, fontSize: 16))
                ],
              ));
        }`

**Comment by yangyxd** [comment]
请参考demo中第 11 个 示例
