### ISSUE TITLE
[bug report] 分屏模式下组件溢出 bug (bottom overflowed)

### ISSUE THREAD

**Issue by kvii2202** [yangyxd/flutter_picker#120]
# 分屏模式下组件溢出 `bottom overflowed` bug

机型： 安卓 华为 麦芒5 android 7.0  

## 描述

使用 picker 的 `show model` 方法时出现的错误。
The bug will occurred when I use `picker.showModel(context)` and split my screen.

安卓虚拟机同样出现此错误，应该不是国内厂商的锅。
The same behavior in the emulator. so I think is not only occurred by third-party OS.

## 屏幕截图 screen shot

- 分屏时发生了错误 bug in the case that on above
![flutter_01](https://user-images.githubusercontent.com/56432636/90959767-9ce77880-e4cf-11ea-9d7d-201988415d9e.png)

- 拉动屏幕后又正常显示了 after I drag my screen, it works good.
![image](https://user-images.githubusercontent.com/56432636/90959880-37e05280-e4d0-11ea-9d7b-5e3aba52f9c6.png)

## 代码 code
``` dart
// 仅仅是个简单的示例实现
class MyBody extends StatefulWidget {
  @override
  _MyBodyState createState() => _MyBodyState();
}

class _MyBodyState extends State<MyBody> {
  String a = '选择';

  @override
  Widget build(BuildContext context) {
    final picker = Picker(
      adapter: PickerDataAdapter<String>(pickerdata: ['a', 'b', 'c']),
      onConfirm: (p, _) => setState(() => a = p.getSelectedValues()[0]),
    );

    return Center(
      child: FlatButton(
        child: Text(a),
        onPressed: () => picker.showModal(context),
      ),
    );
  }
}
```

最后

已解决的 issue 能不能 close 一下，一点进来 70 个 issue… 我还以为你停更跑路了呢 23333.

**Comment by yangyxd** [comment]
争对此问题, 可以从两方面进行解决：
1. 根据实际情况指定 height 属性
2. showModal isScrollControlled 参数设为 true.
