### ISSUE TITLE
修改当前选中条的背景颜色

### ISSUE THREAD

**Issue by 404N** [yangyxd/flutter_picker#135]
flutter版本号：2.0.0
flutter_picker：1.1.5
![image](https://user-images.githubusercontent.com/30525962/112110990-913b6c00-8bee-11eb-8a4a-0969e3358166.png)
能否去除当前选中的黑色背景，或者提供自定义选中条的背景色功能

**Comment by yangyxd** [comment]
增加了 selectionOverlay 参数，可以用来控制这个

**Comment by yangyxd** [comment]
增加了 selectionOverlay 参数，可以用来控制这个

**Comment by 404N** [comment]
好的，谢谢大佬
