### ISSUE TITLE
点击确认按钮后无法打开新页面

### ISSUE THREAD

**Issue by tadpole145** [yangyxd/flutter_picker#137]
version: 1.1.5, 因为我没有升级flutter和dart,不支持2.0.0版本
问题描述: 业务需求,选择确认按钮后,需要将选中的数据作为参数传递到新页面,然而我设置好onConfirm回调后发现,每次新页面打开就关闭,查看源码发现
 /// 确定
  void doConfirm(BuildContext context) {
    if (onConfirm != null) onConfirm(this, selecteds);
    Navigator.of(context).pop();
    _widget = null;
  }
你是先回调,再调用Navigator.of(context).pop();  这样导致我打开新页面里面关闭了....我觉得正确流程应该是先关闭当前弹窗,然后打开新页面....然后我就去自定义confirm控件, 点击后执行关闭,再打开新页面,逻辑确实通了...新的问题产生了,我拿不到picker和选中的那行数据了, 请问我该如何处理呢? 谢谢

**Comment by yangyxd** [comment]
此问题我会在 2.0.1 版修复。谢谢反馈。不升级的话你可以使用 confirm 属性，自己提供一个确认按钮并处理点击事件。

**Comment by tadpole145** [comment]
我最后拷贝了你代码..感谢作者哈
