### ISSUE TITLE
showModal,页面出不来，报错信息如下

### ISSUE THREAD

**Issue by WxiaoM** [yangyxd/flutter_picker#138]
Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2997 pos 18: '!navigator._debugLocked': is not true
我项目里面用的是Scanffod和MaterialApp,为何页面弹不出来

**Comment by yangyxd** [comment]
报谦，你这个问题我也不知道原因。在demo中是可以正常shoModal出来的，你可以自己再检查一下。
