### ISSUE TITLE
默认的初始化时间不对

### ISSUE THREAD

**Issue by youxinLu** [yangyxd/flutter_picker#142]
` showPickerDateTime(BuildContext context) {
    Picker(
        adapter: DateTimePickerAdapter(
          type: PickerDateTimeType.kYMDHM,
          isNumberMonth: true,
          yearSuffix: "年",
          monthSuffix: "月",
          daySuffix: "日",
          minuteInterval: 1,
          minHour: 8,
          maxHour: 20,
          value: new DateTime.now(),
          // twoDigitYear: true,
        ),
        textAlign: TextAlign.right,
        headerColor: AppColors.COLOR_F0F0F0,
        cancelText: AppStrings.CANCEL,
        confirmText: AppStrings.CONFIRM,
        looping:true,
        cancelTextStyle: TextStyle(color:  AppTheme.appThemeData.primaryColor,fontSize: ScreenUtil().setSp(AppDimens.DIMENS_42)),
        confirmTextStyle: TextStyle(color:  AppTheme.appThemeData.primaryColor,fontSize: ScreenUtil().setSp(AppDimens.DIMENS_42)),
        selectionOverlay:null,
        selectedTextStyle: TextStyle(color: Colors.blue),

        onConfirm: (Picker picker, List value) {
          print(value.toString());
          print(picker.adapter.getText());
          // _date = (picker.adapter as DateTimePickerAdapter).value;
        },
        onSelect: (Picker picker, int index, List<int> selecteds) {

        }
    ).showModal(context);
  }`

小时字段默认选中的都是设置的maxHour或者是23

**Comment by yangyxd** [comment]
@youxinLu  谢谢，这个问题将在 2.0.2 中修复，等待更新即可
