### ISSUE TITLE
又一个bug  当只有2列的时候  当第二行的第二列只有一条数据的时候  当第一行第二列滑动到最下面的时候 再滑动到第二行就有bug

### ISSUE THREAD

**Issue by zhoutongbie** [yangyxd/flutter_picker#148]
又一个bug  当只有2列的时候  当第二行的第二列只有一条数据的时候  当第一行第二列滑动到最下面的时候 再滑动到第二行就有bug

**Comment by yangyxd** [comment]
@zhoutongbie “当第二行的第二列只有一条数据的时候” 不是很明白。如果方便，请提供一个demo代码
