### ISSUE TITLE
Clear button or the possibility of hide cancel and confirm buttons

### ISSUE THREAD

**Issue by hanyska** [yangyxd/flutter_picker#150]
I need to add clear button to dialog picker. If I add custom footer and set
`      cancel: SizedBox(height: 0),
      confirm: SizedBox(height: 0),`

There is too much empty space at the end of a section.
Can we be able to hide the automatically generated buttons for our footer?

**Comment by yangyxd** [comment]
Use Picker `makePicker` function. All the other customization will do.

**Comment by yangyxd** [comment]
It's not tested in v2.0.1
