### ISSUE TITLE
使用PickerItem集合渲染级联时候发现一个BUG

### ISSUE THREAD

**Issue by zchuan98660** [yangyxd/flutter_picker#151]
你好，我在使用PickerItem集合渲染级联时候发现一个bug，通过递归将数据源填充给PickerItem集合，比如递归了4级，当第1条数据的第4层没有数据时，滑动到第4层有数据的层级就会报下面这个错： 

<img width="819" alt="微信截图_20210721104319" src="https://user-images.githubusercontent.com/87741894/126422526-bb28c7de-295b-4046-89c7-109f411581e1.png">

第1条数据第4层初始化是就填充一条数据则不存在问题，下面这个是我的数据源：

<img width="440" alt="微信截图_20210721104822" src="https://user-images.githubusercontent.com/87741894/126422816-7fd56d8c-f40d-496e-9fc3-dbf69b87fa11.png">

如果将第四层的数据填充给第一条数据则不会出现上述问题。

**Comment by yangyxd** [comment]
@zchuan98660  能提供一个 demo 出来吗

**Comment by yangyxd** [comment]
暂时关闭
