### ISSUE TITLE
设置了背景颜色 但是四周还是白色的

### ISSUE THREAD

**Issue by TransFormes** [yangyxd/flutter_picker#156]
![image](https://user-images.githubusercontent.com/31639628/131321432-8f482520-114f-4cf9-ab78-db3ef6954138.png)

比如我要设置圆角，四周的白色区域怎么去掉呢

**Comment by ZiY1** [comment]
同問

**Comment by ZiY1** [comment]
![image](https://user-images.githubusercontent.com/74223199/155455843-128b83aa-5d06-4d7d-a84c-7707ae19e5d5.png)
可以直接改Picker.dart 里的 showModalBottomSheet

**Comment by yangyxd** [comment]
可以参考最新的一些demo
