### ISSUE TITLE
minuteInterval设置为30时 选择时间有问题

### ISSUE THREAD

**Issue by Yinllo** [yangyxd/flutter_picker#161]
minuteInterval设置为30时  如果当前时间是 1.11号3:05分，那这个时候选择1.11号5:00时 会变成5:05分

**Comment by Yinllo** [comment]
adapter: DateTimePickerAdapter(
        minValue: minValue,
        isNumberMonth: true,
        customColumnType: [0, 1, 2, 3, 4],
        type: 5,
        yearBegin: 1921,
        yearEnd: 2121,
        minuteInterval: 30,
      )

**Comment by yangyxd** [comment]
谢谢反馈。将会在 2.0.3 中修复此问题。
