### ISSUE TITLE
问题1：selecteds 在设置年、月、日的时候不生效。问题2：滚动会触发苹果的下滑APP手势

### ISSUE THREAD

**Issue by zhengzhong5127** [yangyxd/flutter_picker#177]
触发苹果手势如视频以及设置年份的selected之后选择到了最后面的一列。https://user-images.githubusercontent.com/63284079/175269495-f74e594a-91ea-48da-9b40-8fbcc59e7587.MP4

详见代码`    var picker = Picker(
        selecteds: <int>[1, 1, 2],
        backgroundColor: Colors.transparent,
        height: 216,
        itemExtent: 50,
        cancelText: '取消',
        cancelTextStyle: const TextStyle(
            color: Color.fromRGBO(169, 169, 169, 1),
            fontSize: 16
        ),
        confirmText: '完成',
        confirmTextStyle: const TextStyle(
            color: Colors.black,
            fontSize: 16
        ),
        headerDecoration: const BoxDecoration(
            border:
            Border(bottom: BorderSide(color: Colors.black12, width: 0.5))),
        adapter: DateTimePickerAdapter(
            type: PickerDateTimeType.kYMD,
            isNumberMonth: true,
            yearSuffix: "年",
            monthSuffix: "月",
            yearBegin: DateTime.now().year - 60,
            yearEnd: DateTime.now().year - 18,
            daySuffix: "日"),
        delimiter: [
          PickerDelimiter(
              column: 3,
              child: Container(
                width: 8.0,
                alignment: Alignment.center,
              )),
          // PickerDelimiter(
          //     column: 5,
          //     child: Container(
          //       width: 12.0,
          //       alignment: Alignment.center,
          //       child: Text(':', style: TextStyle(fontWeight: FontWeight.bold)),
          //       color: Colors.white,
          //     )),
        ],
        // title: Text("Select DateTime"),
        onConfirm: (Picker picker, List value) {
          DateTime? timeDate = (picker.adapter as DateTimePickerAdapter).value;

          if (timeDate != null) {

            Log.i('生日：${DateFormat("yyyy-MM-dd").format(timeDate)}');
          }
          print(picker.adapter.text);
        },
        onSelect: (Picker picker, int index, List<int> selected) {
          // showMsg(picker.adapter.toString());
          print(picker.adapter.toString());
          print('object = $selected');
        });
`

**Comment by yangyxd** [comment]
@zhengzhong5127  谢谢。问题1将在 2.0.4 版中修复。问题2不属于此小部件的问题。
