### ISSUE TITLE
Datetimepicker custom buttons

### ISSUE THREAD

**Issue by massimilianochiodi** [yangyxd/flutter_picker#181]
using datetimepicker only for hours and minutes, how can I use a custom button so it can return data?

confirm: TextButton(
        style: ButtonStyle(
            shape: MaterialStateProperty.all<RoundedRectangleBorder>(
                RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(10.0),
                    side: const BorderSide(color: ConstColor.coloreSfondo)
                )
            ),
            backgroundColor:
            MaterialStateProperty.all(ConstColor.coloreSfondo), fixedSize: MaterialStateProperty.all(const Size(100, 44)) ),
        child: Text(AppLocalizations.instance.text("ok"),
            style: const TextStyle(
                fontWeight: FontWeight.bold,
                color: ConstColor.coloreMedium)),
        onPressed: () {
          ?????????????????
          Navigator.of(context).pop();
        },
      ),

**Comment by yangyxd** [comment]
@massimilianochiodi 
please call `picker.doConfirm(context)`. 
This will get the selected value in the `onConfirm` callback.
