### ISSUE TITLE
AM/PM are backward for 12:00

### ISSUE THREAD

**Issue by tkeithblack** [yangyxd/flutter_picker#185]
When using AM/PM mode (PickerDateTimeType.kHM_AP), the AM & PM are backwards.

Selecting 12:00 AM returns 12:00:00.000. It should return 00:00:00.000.
Selecting 12:00 PM returns 00:00:00.000. It should return 12:00:00.000.

This also applies to any minutes within the 12 range. 

Selecting 12:30 AM returns 12:30:00.000.
Selecting 12:30 PM returns 00:30:00.000.

Note: In AM/PM notation AM & PM switch exactly at 12:00. 11:59 = AM, 12:00 = PM

**Comment by MoSala95** [comment]
I can confirm the same issue with me.

**Comment by yangyxd** [comment]
thanks! Will be fixed in v2.1.0.

**Comment by jeetbv** [comment]
This issue is not resolved yet.

When I am trying to select 12:05 AM, it always gives me 12:05 PM.
Please check and help us.
