### ISSUE TITLE
Add the ability to jump numbers in NumberPickerColumn

### ISSUE THREAD

**Issue by jesusrp98** [yangyxd/flutter_picker#22]
Add a new parameter to the `NumberPickerColumn` class, called `jump`, that would skip `n` numbers.
For example:
- `NumberPickerColumn(begin: 100, end: 500)` returns `100, 101, 102 ,..., 499, 500`.
- `NumberPickerColumn(begin: 100, end: 500, jump: 100)` would return `100, 200, 300, 400, 500`.

**Comment by yangyxd** [comment]
OK, practical functions, I will add as soon as possible.

**Comment by yangyxd** [comment]
Thanks.

**Comment by jesusrp98** [comment]
Great! Glad you liked it. :)
