### ISSUE TITLE
请问可以增加配置中间的分割线颜色吗

### ISSUE THREAD

**Issue by didyqian** [yangyxd/flutter_picker#30]
如题，请问可以增加配置中间的分割线颜色吗？像配置标题分割线那样

**Comment by yangyxd** [comment]
不支持

**Comment by yangyxd** [comment]
这个现在已经可以通过 selectionOverlay 选项实现了。

**Comment by zhaoxiuyu** [comment]
@yangyxd 如何去掉中间的分割线。。

**Comment by PierreVon** [comment]
> 如题，请问可以增加配置中间的分割线颜色吗？像配置标题分割线那样

请问标题分割线咋配置呀？
