### ISSUE TITLE
改变上级数据，下级数据显示空白

### ISSUE THREAD

**Issue by DemoJameson** [yangyxd/flutter_picker#48]
![GIF](https://user-images.githubusercontent.com/181192/60869696-05d74700-a262-11e9-89dd-644ddc317d76.gif)
如果所示，当选择7月22号或之后的日期时选择8月份，无法自动滚到8月9号。期望与选择7月21号时一样可以自动滚到8月最后一个数据即8月9号。

    showYmdDialog(context, DateTime.now().add(Duration(days: 1)), DateTime.now().add(Duration(days: 31)), (value) {});

	void showYmdDialog(BuildContext context, DateTime startDate, DateTime endDate, Function onConfirm) {
	  int lastDayOfMonth(DateTime date) {
	    return DateTime(date.year, date.month + 1, 0).day;
	  }
	
	  List<PickerItem<String>> generatePickerData(DateTime startDate, DateTime endDate) {
	    List<PickerItem<String>> pickerData = [];
	    int limitDay = endDate
	        .difference(startDate)
	        .inDays;
	
	    var date = startDate;
	    for (var year = startDate.year; year <= endDate.year; year++) {
	      // 年
	      PickerItem<String> yearItem = PickerItem(
	        text: Center(child: Text(year.toString())),
	        value: year.toString(),
	        children: [],
	      );
	      pickerData.add(yearItem);
	      for (var month = date.month; month <= 12; month++) {
	        // 月
	        PickerItem<String> monthItem = PickerItem(
	          text: Center(child: Text(month.toString())),
	          value: month.toString(),
	          children: [],
	        );
	        yearItem.children.add(monthItem);
	        while (date.day <= lastDayOfMonth(date)) {
	          // 日
	          PickerItem<String> dayItem = PickerItem(
	            text: Center(child: Text(date.day.toString())),
	            value: date.day.toString(),
	          );
	          monthItem.children.add(dayItem);
	
	          date = date.add(Duration(days: 1));
	          limitDay--;
	
	          if (limitDay < 0) {
	            return pickerData;
	          }
	
	          if (date.day == 1) {
	            break;
	          }
	        }
	      }
	    }
	
	    return pickerData;
	  }
	
	  List<PickerItem<String>> pickerData = generatePickerData(startDate, endDate);
	
	  Picker(
	      adapter: PickerDataAdapter(data: pickerData),
	      confirmText: '确认',
	      cancelText: '取消',
	      textStyle: TextStyle(color: Colors.black, fontSize: 14.0),
	      cancelTextStyle: TextStyle(fontSize: 16.0, color: ColorValues.greyFF9C9C9C),
	      confirmTextStyle: TextStyle(fontSize: 16.0, color: ColorValues.blueFF3A94F9),
	      onConfirm: (Picker picker, List value) {
	        onConfirm(picker.adapter.getSelectedValues().map((text) => text.toString().padLeft(2, "0")).join("-"));
	      },
	      onCancel: () {
	        print('取消');
	      }).showModal(context);
	}

**Comment by skysukai** [comment]
城市选择器遇到了相同的问题。
比如在一级目录“重庆市”选择最后一个item“巫溪县”，快速滚动一级目录到“澳门市”，二级目录显示空白。

**Comment by yangyxd** [comment]
谢谢反馈，已经更正。
