### ISSUE TITLE
如何给picker传入选中行，类似1，2，3行。传入2，picker弹出后，2所在的行默认选中，看了源码好像不支持

### ISSUE THREAD

**Issue by wangyuuuu** [yangyxd/flutter_picker#52]

**Comment by dxjdqc** [comment]
> _No description provided._

请问问题解决了吗

**Comment by dxjdqc** [comment]
可以默认选中的，因为换工作项目代码现在没有了，现在也没写过flutter了，所以没办法帮到你，不好意思啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangyxd/flutter_picker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 中午11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangyxd/flutter_picker] 如何给picker传入选中行，类似1，2，3行。传入2，picker弹出后，2所在的行默认选中，看了源码好像不支持 (#52)





 
Closed #52.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
