### ISSUE TITLE
运行在ios 可以，android上无法运行

### ISSUE THREAD

**Issue by lxk123** [yangyxd/flutter_picker#58]
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_picker'.
> Could not resolve all artifacts for configuration ':flutter_picker:classpath'.
   > Could not download guava.jar (com.google.guava:guava:22.0)
      > Could not get resource 'https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.jar'.
            > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
  Command: /Users/luo_xue_kun/flutter_bridge/flutter_mode/.android/gradlew app:properties

**Comment by yangyxd** [comment]
这个看起来和插件没有什么关系。
