### ISSUE TITLE
textStyle是用来控制选项文本样式的吗？好像不起作用

### ISSUE THREAD

**Issue by zhyf08** [yangyxd/flutter_picker#68]
`
    Picker picker1 = Picker(
        adapter: PickerDataAdapter(data: goodsList),
        cancelText: '取消',
        confirmText: '确定',
        selecteds: [],
        height: 280,
        itemExtent: 38.0,
        changeToFirst: true,
        textAlign: TextAlign.left,
        textStyle: const TextStyle(color: Colors.red, fontSize: 9.0),
        columnPadding: const EdgeInsets.all(8.0),
        onConfirm: (Picker picker, List value) async {
          print(value.toString());
        }
    );`
是我用得不对吗？
现在这个版本的flutter_picker选项字号很大，我想让它能缩小一点，以前版本的挺正常的，不知道是不是我升级了flutter造成的
我尝试设置 textStyle: const TextStyle(color: Colors.red, fontSize: 9.0), 但既不变色，字号也不缩小
![微信图片_20191101173631](https://user-images.githubusercontent.com/39288734/68016047-a1d40500-fcce-11e9-93c4-74fab8b1d311.jpg)
知道的请指教一二，谢谢

**Comment by zhyf08** [comment]
Picker picker1 = Picker(
        adapter: PickerDataAdapter(data: goodsList),
        cancelText: '取消',
        confirmText: '确定',
        selecteds: [],
        changeToFirst: true,
        height: 280,
        itemExtent: 38.0,
        textAlign: TextAlign.left,
        textStyle: const TextStyle(color: Colors.red, fontSize: 9.0),
        columnPadding: const EdgeInsets.all(8.0),
        onConfirm: (Picker picker, List value) async {
          print(value.toString());
        }
    );

“取消”和“确定”的字号倒是可以设置。

**Comment by Nirvana-cn** [comment]
It can be work like this.
```
PickerItem(
    text: Text(
        "text",
        style: TextStyle(color: Colors.white),
     ),
     value: 6,
)   
```

**Comment by fnfufnfu** [comment]
`new Picker(
                  /// 1初中及以下 2中专/技校 3高中 4大专 5本科 6硕士 7博士
                  /// 1全日制 2非全日制
                    adapter: PickerDataAdapter<int>(data: [
                      new PickerItem(text: wrapItem("初中及以下"), value: 1, children:emptyChilds),
                      new PickerItem(text: wrapItem("中专/技校"), value: 2, children:emptyChilds),
                      new PickerItem(text: wrapItem("高中"), value: 3, children: childs),
                      new PickerItem(text: wrapItem("大专"), value: 4, children: childs),
                      new PickerItem(text: wrapItem("本科"), value: 5, children: childs),
                      new PickerItem(text: wrapItem("硕士"), value: 6, children: childs),
                      new PickerItem(text: wrapItem("博士"), value: 7, children: childs),
                    ]),

                    title: new Text("学历"),
                    confirmText: "确定",
                    confirmTextStyle: TextStyle(
                        color: Theme.of(context).primaryColor
                    ),
                    cancelText: "取消",
                    cancelTextStyle: TextStyle(
                        color: Colors.grey
                    ),
                    backgroundColor: Colors.transparent,
                    headercolor: Theme.of(context).dialogBackgroundColor,
/// 没效果 No effect why？
                    textStyle: TextStyle(
                      color: Colors.red
                    ),
/// 没效果 No effect why？
                    selectedTextStyle: TextStyle(
                      color: Colors.deepOrange
                    ),
                    onConfirm: (Picker picker, List value) {

                    },
                    selecteds: <int>[2,0]
                ).showModal(context);`
