### ISSUE TITLE
省市区三级选择栏

### ISSUE THREAD

**Issue by chrischen0405** [yangyxd/flutter_picker#72]
省市区三级选择栏是不是没有类似PickerDataAdapter的封装好的adapter？想要实现省市区的选择功能需要自己写一个adapter？

**Comment by yangyxd** [comment]
没有封装好的

**Comment by MilkBiscuit** [comment]
写一个再建 Pull Request 呀，这样大家就都能用了。

**Comment by MilkBiscuit** [comment]
> 省市区三级选择栏是不是没有类似PickerDataAdapter的封装好的adapter？想要实现省市区的选择功能需要自己写一个adapter？

你写一个再建 Pull Request 呀，这样大家就都能用了。
