### ISSUE TITLE
Add the ability to jump minutes in DateTimePickerAdapter

### ISSUE THREAD

**Issue by MoacirSchmidt** [yangyxd/flutter_picker#76]
Simular to issue #22 

Could you please add a new parameter (like minuteInterval, existing in CupertinoDatePiker) to list minutes in intervals?

This way, user could select time in intervals of 30min, 5mins,  etc....

Congratulations for your exceptional widget!

Thank you in advance!

**Comment by yangyxd** [comment]
@MoacirSchmidt Ha ha, yes, it's a good suggestion.
