### ISSUE TITLE
Publish a new version to 1.1.3

### ISSUE THREAD

**Issue by harsimranmaan** [yangyxd/flutter_picker#84]
Hi, 
I want to use the reuturntype from show dialog. Could you publish the new package version to 1.1.3?

**Comment by yangyxd** [comment]
It's really not easy to publish to pub. I tried several VPN tools all morning and finally succeeded

**Comment by harsimranmaan** [comment]
I can help u write a GitHub action for that if u like

**Comment by harsimranmaan** [comment]
Thanks
