### ISSUE TITLE
feature request: maxHour / minHour for DateTimePickerAdapter

### ISSUE THREAD

**Issue by dexcell** [yangyxd/flutter_picker#87]
Hi your library works great. Thank you.

However i have a request to limit the hour for datetime adapter picker,
So for example, user can only select from 8am to 5pm, instead 24hours.

<img width="287" alt="Screen Shot 2020-03-24 at 11 12 59" src="https://user-images.githubusercontent.com/41800/77387653-99d14a80-6dc0-11ea-8042-e71cdc230fe6.png">

Thanks

**Comment by aries-works** [comment]
You can use min and max? 
```
adapter: new DateTimePickerAdapter(
    minValue: DateTime.now(),
    maxValue: DateTime.now(),
),
```
You can just replace current date time to current date with 8am and 5pm for min and max.

**Comment by dexcell** [comment]
> You can use min and max?
> 
> ```
> adapter: new DateTimePickerAdapter(
>     minValue: DateTime.now(),
>     maxValue: DateTime.now(),
> ),
> ```
> 
> Just replace current date time to current date with 8am and 5pm for min and max.

I don't think you can do it since it will limit the date it'self.
I don't want to limit the date, i just want to limit the hour. 

For example, you want to choose a meeting time but only from 9am-5pm.
But you don't want to limit the date.

Thanks

**Comment by yangyxd** [comment]
This feature has been added.
