### ISSUE TITLE
Datepicker 12 pm/am Bug

### ISSUE THREAD

**Issue by aries-works** [yangyxd/flutter_picker#98]
Datepicker returns wrong value when choosing 12am or pm.

![Screenshot_20200506-214008](https://user-images.githubusercontent.com/7146454/81190579-97325980-8fea-11ea-82e8-97c00c896300.jpg)

**Comment by yangyxd** [comment]
@aries-works thanks! Your app looks good. I tried and found no similar problems. Can you provide related demo?
