### ISSUE TITLE
1.1.4 linkage bug

### ISSUE THREAD

**Issue by dsmjoy** [yangyxd/flutter_picker#99]
1.1.4 linkage 如果层级小于3, 显示出来的两栏一样的

描述的比较简单, 可以用1.1.4 试试 demo里的 showPickerIcons方法

**Comment by yg7001** [comment]
我也发现此问题，降级回1.1.3使用了

**Comment by yangyxd** [comment]
这个问题修复了，谢谢大家

**Comment by RichyLeo** [comment]
@yangyxd 我更新到了1.1.5版本，2级的linkage  调用 -showModalPicker 依然有这个问题

**Comment by yangyxd** [comment]
@RichyLeo 我试了下没重现出来，请提供一下出错的代码

**Comment by RichyLeo** [comment]
> @RichyLeo 我试了下没重现出来，请提供一下出错的代码

抱歉，是个人问题！！1.1.5版本已修复此问题

**Comment by RichyLeo** [comment]
> @RichyLeo 我试了下没重现出来，请提供一下出错的代码

抱歉，是个人问题！！1.1.5版本已修复此问题
